name: airbnb-new-user-bookings
channels:
  - https://conda.anaconda.org/menpo
  - conda-forge
dependencies:
  - python==3.6.1
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - scikit-learn
  - scipy
  - pip:
    - argparse
    - feather-format
    - imbalanced-learn
    - tqdm
